/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ordem_servico;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leonardo
 */
public class Frame_produto extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Consultar
     */
    
    DefaultTableModel modelotabela =  (DefaultTableModel)  (new DefaultTableModel());
                
    public Frame_produto() {
        initComponents();
        jTextField3.setEditable(false);
        DefaultTableModel modelotabela = (DefaultTableModel) (new DefaultTableModel(){public boolean isCellEditable(int row, int column){return false;}});
        jTable1.setModel(modelotabela);
        
        modelotabela.setColumnCount(3);
        modelotabela.setRowCount(0);
        
         jTable1.getColumnModel().getColumn(0).setHeaderValue("Cor");
         jTable1.getColumnModel().getColumn(1).setHeaderValue("Quantidade");
         jTable1.getColumnModel().getColumn(2).setHeaderValue("Tamanho");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setText("Valor Venda:");

        jLabel9.setText("Categoria:");

        jButton2.setText("Alterar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel1.setText("Rererência:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("FICHA DO PRODUTO");

        jLabel2.setText("Descrição:");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jLabel12.setText("Referência:");

        jButton1.setText("Cadastrar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("CONSULTA");

        jButton5.setText("Fechar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jLabel4.setText("Valor Compra:");

        jButton3.setText("Consultar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel5.setText("Cor:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox1FocusLost(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Quantidade:");

        jLabel7.setText("Tamanho:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel13.setText("Margem:");

        jLabel14.setText("R$");

        jLabel15.setText("R$");

        jButton4.setText("Calcular");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
        });

        jButton6.setText("Limpar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton7.setText("Excluir");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("ESTOQUE");

        jButton8.setText("Adicionar");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jButton9.setText("Remover");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(35, 35, 35))
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox1, 0, 150, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addComponent(jLabel11)
                    .addComponent(jLabel16)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addGap(26, 26, 26)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel15)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel14)
                                    .addComponent(jButton4)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(20, 20, 20))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton7)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9)
                            .addComponent(jButton8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...","Blusa", "Calça", "Saia", "Shorts", "Vestido", "Macação", "Macaquinho","Body","Top","Chopped","Camisa","Jaqueta","Chapéu","Bolsa","Carteira","Anel","Brinco","Gargantilha","Pulseira","Cinto","Lenço","Bracelete","Coleira","Boné" }));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Selecione...", "Preto", "Branco", "Offwhite", "Dourado","Prata","Rosa","Azul","Verde","Amarelo","Terra","Marsala","Jeans","Coral","Militar","Turquesa","Pêssego","Laranja","Azul Marinho","Fendi","Estampado" }));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Selecione...", "PP", "P", "M", "G","GG" }));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
       dados d = new dados();
        
            if (d.conecta()){
                System.out.println("Conectado com sucesso!");
            }else {
                System.out.println("Erro ao conectar!");
            }
            
        ResultSet rs = null;
        
        rs = d.consulta("select * from cprodutos where referencia = '"+jTextField10.getText()+"'");
        
        try {
            while (rs.next()){
                d.atualiza("cprodutos", "categoria = '"+jComboBox1.getSelectedItem()+"'", "referencia = '"+jTextField10.getText()+"'");
                d.atualiza("cprodutos", "descricao = '"+jTextArea2.getText()+"'", "referencia = '"+jTextField10.getText()+"'");
                d.atualiza("cprodutos", "descricao = '"+jTextArea2.getText()+"'", "referencia = '"+jTextField10.getText()+"'");
                d.atualiza("cprodutos", "valor_compra = '"+jTextField2.getText()+"'", "referencia = '"+jTextField10.getText()+"'");
                d.atualiza("cprodutos", "margem = '"+jTextField5.getText()+"'", "referencia = '"+jTextField10.getText()+"'");
                d.atualiza("cprodutos", "valor_venda = '"+jTextField3.getText()+"'", "referencia = '"+jTextField10.getText()+"'");
                d.atualiza("cprodutos", "referencia = '"+jTextField1.getText()+"'", "referencia = '"+jTextField10.getText()+"'");
            }
        }catch(Exception e){
            System.out.println("Houve um erro: "+e);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed

    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        dados d = new dados();

        d.conecta();

        if (!jTextField1.getText().isEmpty() && !jComboBox1.getSelectedItem().equals("Selecione...")){
            String codigo =(jTextField1.getText().toUpperCase());
            d.insere_produto("cprodutos", (String)jComboBox1.getSelectedItem(),codigo, jTextArea2.getText(),jTextField2.getText(),jTextField5.getText(),jTextField3.getText());
        }else{
            JOptionPane.showMessageDialog(rootPane, "DIGITE A REFERÊNCIA E SELECIONE UMA CATEGORIA!", "ERRO", WIDTH, null);
        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked

        setVisible(false);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jComboBox1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusLost
        if (jComboBox1.getSelectedItem().equals("Calçado")){
            jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "34", "35", "36", "37", "38", "39"
            , "40", "41", "42"}));
        }
    }//GEN-LAST:event_jComboBox1FocusLost

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        if ((!jTextField2.getText().isEmpty()) && (!jTextField5.getText().isEmpty())){         
            String vc = jTextField2.getText();
            vc = vc.replaceAll(",", ".");          
            String margem = jTextField5.getText();
            margem = margem.replaceAll(",", ".");          
            jTextField3.setText(String.valueOf(Double.parseDouble(margem) * Double.parseDouble(vc)) );
        } else{
            JOptionPane.showMessageDialog(rootPane, "DIGITE O VALOR DE COMPRA E A MARGEM!", "AVISO", WIDTH);
        }
            
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
                
            dados d = new dados();
        
            if (d.conecta()){
                System.out.println("Conectado com sucesso!");
            }else {
                System.out.println("Erro ao conectar!");
            }
            ResultSet rs = null;
            
            rs = d.consulta("select count(*) from cprodutos where referencia = '"+jTextField1.getText()+"'");
            
            try {
                while(rs.next()){
                    
                    if (!jTextField1.getText().isEmpty() && !rs.getString("count(*)").equals("0")){
                        
                         rs = d.consulta("select cod_produto from cprodutos where referencia = '"+jTextField1.getText()+"'");
            
                            try {
                                while (rs.next()){
                                    d.insere_estoque("cestoque",rs.getString("cod_produto"), (String)jComboBox2.getSelectedItem(), 
                                            Integer.parseInt(jTextField4.getText()), (String) jComboBox3.getSelectedItem()); 
                                }

                            }catch(Exception e){
                                System.out.print("Houve um erro: "+e);
                            }
                        
                            rs = d.consulta("select cor,quantidade,tamanho "
                           + "from cestoque "
                           + "where cod_produto = ("
                           + "select cod_produto "
                           + "from cprodutos "
                           + "where referencia = '"+jTextField1.getText()+"')");
            
                            jTable1.setModel(modelotabela);
                            modelotabela.setColumnCount(3);
                            modelotabela.setRowCount(0);
            
                            jTable1.getColumnModel().getColumn(0).setHeaderValue("Cor");
                            jTable1.getColumnModel().getColumn(1).setHeaderValue("Quantidade");
                            jTable1.getColumnModel().getColumn(2).setHeaderValue("Tamanho");
            
                                int linha = 0;
                                try{
                                    while (rs.next()){       
                                        modelotabela.addRow(new String [modelotabela.getColumnCount()]);
                                        modelotabela.setValueAt(rs.getString("cor"),linha,0);
                                        modelotabela.setValueAt(rs.getString("quantidade"),linha,1);
                                        modelotabela.setValueAt(rs.getString("tamanho"),linha,2);
                                        linha = linha+1;
                                    }
                                }catch(Exception e){
                                   System.out.print("Houve um erro: "+e);
                                }
                
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "NENHUM REGISTRO ENCONTRADO PARA REALIZAR A OPERAÇÃO!", null, WIDTH);
                    }
                    
                }                
            }catch (Exception e){
                System.out.println("Houve um erro: "+e);
            }
            
            
           
            
            
         
            
            
                
                
   
               
                
                
                //linha = modelotabela.getRowCount()+1;
               
                
                
                
                
                //modelotabela.setValueAt(jComboBox2.getSelectedItem(), linha, 0);
                
             
                
                //modelotabela.addRow(new String [modelotabela.getColumnCount()]);
                //modelotabela.setValueAt(jComboBox2.getSelectedItem(),0,0);
                //modelotabela.setValueAt(retorno.getString("preco"),linha,1);
               // modelotabela.setValueAt(retorno.getString("quantidade"),linha,2);
               
                
                
            
            
        
        
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
         dados d = new dados();
        
        if (d.conecta()){
            System.out.println("Conectado com sucesso!");
        }else {
            System.out.println("Erro ao conectar!");
        }
        
        ResultSet rs = null;
                
        if (!jTextField1.getText().isEmpty()){
            rs = d.consulta("select count(*) from cprodutos where referencia like '"+jTextField1.getText()+"'"); 
            
            try{
                while(rs.next()){
                    if (rs.getString("count(*)").equals("1")){
                        int resp = 0;
                        resp = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja excluir?", "Confirmar", resp, WIDTH);
                         if (resp==JOptionPane.YES_OPTION){
                             d.exclui("cprodutos", "referencia = '"+jTextField1.getText()+"'");
                             JOptionPane.showMessageDialog(rootPane, "EXCLUIDO COM SUCESSO!", "AVISO", resp);
                             jTextField10.setText(null);
                             jComboBox1.setSelectedIndex(0);
                             jComboBox2.setSelectedIndex(0);
                             jComboBox3.setSelectedIndex(0);
                             jTextField1.setText(null);
                             jTextField2.setText(null);
                             jTextField3.setText(null);
                             jTextField4.setText(null);
                             jTextField5.setText(null);
                             jTextArea2.setText(null);
                             jTable1.setModel(modelotabela);
                         }else{
                             JOptionPane.showMessageDialog(rootPane, "NENHUM REGISTRO FOI ALTERADO!", "AVISO", resp);
                         }


                    }
                }
            
            }catch(Exception e){
                System.out.println("Houve um erro: "+e);
            }
        }else{
          JOptionPane.showMessageDialog(rootPane, "NENHUM REGISTRO SELECIONADO!", "AVISO", WIDTH);  
        }
            
        
        
        
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        jTextField10.setText(null);
                             jComboBox1.setSelectedIndex(0);
                             jComboBox2.setSelectedIndex(0);
                             jComboBox3.setSelectedIndex(0);
                             jTextField1.setText(null);
                             jTextField2.setText(null);
                             jTextField3.setText(null);
                             jTextField4.setText(null);
                             jTextField5.setText(null);
                             jTextArea2.setText(null);
                              DefaultTableModel modelotabela = (DefaultTableModel) (new DefaultTableModel(){public boolean isCellEditable(int row, int column){return false;}});
                             jTable1.setModel(modelotabela);
                            
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        dados d = new dados();
        
        if (d.conecta()){
            System.out.println("Conectado com sucesso!");
        }else {
            System.out.println("Erro ao conectar!");
        }
        
        ResultSet rs = null;
        
        rs = d.consulta("select * from cprodutos where referencia = '"+jTextField10.getText()+"'");
        
        try {
            
            while(rs.next()){
                jComboBox1.setSelectedItem(rs.getString("categoria"));
                jTextField1.setText(rs.getString("referencia"));
                jTextArea2.setText(rs.getString("descricao"));
                jTextField2.setText(rs.getString("valor_compra"));
                jTextField5.setText(rs.getString("margem"));
                jTextField3.setText(rs.getString("valor_venda"));
            }
            
        }catch (Exception e){
            System.out.println("Houve um erro: "+e);
        }
        
        rs = d.consulta("select count(*) from cprodutos where referencia = '"+jTextField1.getText()+"'");
        
        try {
                while(rs.next()){
                    
                    if (!jTextField1.getText().isEmpty() && !rs.getString("count(*)").equals("0")){
                        
                            rs = d.consulta("select cor,quantidade,tamanho "
                           + "from cestoque "
                           + "where cod_produto = ("
                           + "select cod_produto "
                           + "from cprodutos "
                           + "where referencia = '"+jTextField1.getText()+"')");
            
                            jTable1.setModel(modelotabela);
                            modelotabela.setColumnCount(3);
                            modelotabela.setRowCount(0);
            
                            jTable1.getColumnModel().getColumn(0).setHeaderValue("Cor");
                            jTable1.getColumnModel().getColumn(1).setHeaderValue("Quantidade");
                            jTable1.getColumnModel().getColumn(2).setHeaderValue("Tamanho");
            
                                int linha = 0;
                                try{
                                    while (rs.next()){       
                                        modelotabela.addRow(new String [modelotabela.getColumnCount()]);
                                        modelotabela.setValueAt(rs.getString("cor"),linha,0);
                                        modelotabela.setValueAt(rs.getString("quantidade"),linha,1);
                                        modelotabela.setValueAt(rs.getString("tamanho"),linha,2);
                                        linha = linha+1;
                                    }
                                }catch(Exception e){
                                   System.out.print("Houve um erro: "+e);
                                }
                
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "NENHUM REGISTRO ENCONTRADO PARA REALIZAR A OPERAÇÃO!", null, WIDTH);
                    }
                    
                }                
            }catch (Exception e){
                System.out.println("Houve um erro: "+e);
            }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
         dados d = new dados();
        
        if (d.conecta()){
            System.out.println("Conectado com sucesso!");
        }else {
            System.out.println("Erro ao conectar!");
        }
        
        
        
        
    }//GEN-LAST:event_jButton9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_produto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
